version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    command: celery -A services.stt_service worker --loglevel=info 
    volumes:
      - ./app:/app

  flower:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "5555:5555"
    volumes:
      - ./app:/app
    environment:
      - PYTHONPATH=/app
    command: >
      celery -A services.stt_service:celery_app flower --port=5555
    depends_on:
      - redis
      - celery